language: c

sudo: required

python:
  - 2.7

install:
  - git clone git://github.com/msembinelli/mpm.git
  - cd mpm
  - pip install --user .
  - cd ..
  - mpm load -p travis
  - pip install --user -U pip
  - pip install --user urllib3[secure]
  - pip install --user cpp-coveralls

# command to run tests
script:
  make

after_success:
  coveralls --exclude test/ -n
