language: c

sudo: required

python:
  - 2.7

install:
  - pip install --user -U pip
  - pip install --user urllib3[secure]
  - pip install --user cpp-coveralls

# command to run tests
script:
  make
after_success:
  coveralls --exclude lib --exclude tests --gcov-options '\-lp'
