language: c

sudo: required

python:
  - 2.7.12

install:
  - pip install -U pip
  - pip install urllib3[secure]
  - pip install cpp-coveralls

# command to run tests
script:
  make
after_success:
  coveralls --exclude lib --exclude tests --gcov-options '\-lp'
